#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════
# setup_dhcp_server.sh — Configure the DHCP Server VM
#
# Run this on the DHCP Server VM to install and configure isc-dhcp-server
# to assign local IPs to Client and Attacker VMs.
#
# Usage: sudo ./setup_dhcp_server.sh <interface> [subnet] [range_start] [range_end]
#
# Example:
#   sudo ./setup_dhcp_server.sh eth0
#   sudo ./setup_dhcp_server.sh eth0 192.168.100.0 192.168.100.100 192.168.100.200
# ═══════════════════════════════════════════════════════════════════════

set -euo pipefail

IFACE="${1:-eth0}"
SUBNET="${2:-192.168.100.0}"
RANGE_START="${3:-192.168.100.100}"
RANGE_END="${4:-192.168.100.200}"
SERVER_IP="${5:-192.168.100.1}"
NETMASK="255.255.255.0"
LEASE_TIME="600"          # 10 minutes
MAX_LEASE_TIME="7200"     # 2 hours

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

if [[ $EUID -ne 0 ]]; then
    err "This script must be run as root"
fi

# ── Assign static IP to DHCP server interface ───────────────────────
info "Configuring $IFACE with IP $SERVER_IP/24..."
ip addr flush dev "$IFACE" 2>/dev/null || true
ip addr add "$SERVER_IP/24" dev "$IFACE"
ip link set "$IFACE" up
ok "Interface $IFACE configured"

# ── Install isc-dhcp-server ─────────────────────────────────────────
info "Installing isc-dhcp-server..."
apt-get update -qq
apt-get install -y -qq isc-dhcp-server
ok "isc-dhcp-server installed"

# ── Configure dhcpd.conf ────────────────────────────────────────────
info "Writing /etc/dhcp/dhcpd.conf..."
cat > /etc/dhcp/dhcpd.conf <<EOF
# ═══════════════════════════════════════════════════════════════
# DHCP Server Configuration for XDP Layer-2 Security Testbed
# Generated by setup_dhcp_server.sh
# ═══════════════════════════════════════════════════════════════

# Global settings
default-lease-time ${LEASE_TIME};
max-lease-time ${MAX_LEASE_TIME};

# Authoritative — this is the only DHCP server on this network
authoritative;

# Log all DHCP transactions
log-facility local7;

# Subnet definition
subnet ${SUBNET} netmask ${NETMASK} {
    range ${RANGE_START} ${RANGE_END};
    option routers ${SERVER_IP};
    option subnet-mask ${NETMASK};
    option domain-name "xdp-testbed.local";
    option domain-name-servers 8.8.8.8, 8.8.4.4;
    option broadcast-address $(echo "$SUBNET" | sed 's/\.0$/.255/');
}
EOF
ok "dhcpd.conf written"

# ── Configure the listening interface ───────────────────────────────
info "Setting DHCP server to listen on $IFACE..."
cat > /etc/default/isc-dhcp-server <<EOF
INTERFACESv4="${IFACE}"
INTERFACESv6=""
EOF
ok "Listening interface set to $IFACE"

# ── Restart DHCP server ─────────────────────────────────────────────
info "Starting isc-dhcp-server..."
systemctl restart isc-dhcp-server
systemctl enable isc-dhcp-server

if systemctl is-active --quiet isc-dhcp-server; then
    ok "DHCP server is running"
else
    err "DHCP server failed to start. Check: journalctl -u isc-dhcp-server"
fi

# ── Summary ──────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║              DHCP Server Configuration Complete             ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Interface:    $IFACE"
echo "║  Server IP:    $SERVER_IP"
echo "║  Subnet:       $SUBNET / $NETMASK"
echo "║  DHCP Range:   $RANGE_START — $RANGE_END"
echo "║  Lease Time:   $LEASE_TIME seconds"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  On Client/Attacker VMs, run:                               ║"
echo "║    sudo dhclient <interface>                                ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Show current leases
echo "Current leases:"
cat /var/lib/dhcp/dhcpd.leases 2>/dev/null || echo "(none yet)"
